### ISSUE TITLE
Ability to set bridge IP manually

### ISSUE THREAD

**Issue by nylki** [blitzcode/hue-dashboard#1]
hue-dashboard fails to discover the bridge in my network. It is not connected to the internet, therefore the discovery method via the broker server will fail.

A possible fix might be to at a cmdline parameter to set the IP-address of the bridge manually or alternatively do a quick port scan on the current network if discovery fails otherwise.

**Comment by blitzcode** [comment]
There's a commit adding a command line flag for specifying the IP manually on the `threepenny-fixes` branch. I think you can also specify a hostname, all bridges should have one. At some point it might make sense to implement the alternate UPnP based bridge discovery method as well.

**Comment by nylki** [comment]
Thank you, the `threepenny-fixes` branch works fine!
